// Link server kết nối thông qua CDN JSDelivr dựa trên kho GitHub tckzone của bạn
const cloudStorageUrl = "https://cdn.jsdelivr.net/gh/tckzone/hoctiengviet@main/";

const database = [
    // === BẢNG ÂM ĐƠN ===
    { word: "a", mean: "字母 a / A", group: "chu_cai", file: "a.mp3" },
    { word: "ă", mean: "字母 ă / Ă", group: "chu_cai", file: "ă.mp3" },
    { word: "â", mean: "字母 â / Â", group: "chu_cai", file: "â.mp3" },
    { word: "b", mean: "字母 b / B", group: "chu_cai", file: "b.mp3" },
    { word: "c", mean: "字母 c / C", group: "chu_cai", file: "c.mp3" },
    { word: "d", mean: "字母 d / D", group: "chu_cai", file: "d.mp3" },
    { word: "đ", mean: "字母 đ / Đ", group: "chu_cai", file: "đ.mp3" },
    { word: "e", mean: "字母 e / E", group: "chu_cai", file: "e.mp3" },
    { word: "ê", mean: "字母 ê / Ê", group: "chu_cai", file: "ê.mp3" },
    { word: "g", mean: "字母 g / G", group: "chu_cai", file: "g.mp3" },
    { word: "h", mean: "字母 h / H", group: "chu_cai", file: "h.mp3" },
    { word: "i", mean: "字母 i / I", group: "chu_cai", file: "i.mp3" },
    { word: "k", mean: "字母 k / K", group: "chu_cai", file: "k.mp3" },
    { word: "l", mean: "字母 l / L", group: "chu_cai", file: "l.mp3" },
    { word: "m", mean: "字母 m / M", group: "chu_cai", file: "m.mp3" },
    { word: "n", mean: "字母 n / N", group: "chu_cai", file: "n.mp3" },
    { word: "o", mean: "字母 o / O", group: "chu_cai", file: "o.mp3" },
    { word: "ô", mean: "字母 ô / Ô", group: "chu_cai", file: "ô.mp3" },
    { word: "ơ", mean: "字母 ơ / Ơ", group: "chu_cai", file: "ơ.mp3" },
    { word: "p", mean: "字母 p / P", group: "chu_cai", file: "p.mp3" },
    { word: "q", mean: "字母 q / Q", group: "chu_cai", file: "q.mp3" },
    { word: "r", mean: "字母 r / R", group: "chu_cai", file: "r.mp3" },
    { word: "s", mean: "字母 s / S", group: "chu_cai", file: "s.mp3" },
    { word: "t", mean: "字母 t / T", group: "chu_cai", file: "t.mp3" },
    { word: "u", mean: "字母 u / U", group: "chu_cai", file: "u.mp3" },
    { word: "ư", mean: "字母 ư / Ư", group: "chu_cai", file: "ư.mp3" },
    { word: "v", mean: "字母 v / V", group: "chu_cai", file: "v.mp3" },
    { word: "x", mean: "字母 x / X", group: "chu_cai", file: "x.mp3" },
    { word: "y", mean: "字母 y / Y", group: "chu_cai", file: "y.mp3" },

    // === PHỤ ÂM GHÉP ĐẦU ===
    { word: "ch", mean: "辅音 ch", group: "phu_am", file: "ch.mp3" },
    { word: "kh", mean: "辅音 kh", group: "phu_am", file: "kh.mp3" },
    { word: "th", mean: "辅音 th", group: "phu_am", file: "th.mp3" },
    { word: "nh", mean: "辅音 nh", group: "phu_am", file: "nh.mp3" },
    { word: "ph", mean: "辅音 ph", group: "phu_am", file: "ph.mp3" },
    { word: "gh", mean: "辅音 gh", group: "phu_am", file: "gh.mp3" },
    { word: "ng", mean: "辅音 ng", group: "phu_am", file: "ng.mp3" },
    { word: "qu", mean: "辅音 qu", group: "phu_am", file: "qu.mp3" },
    { word: "tr", mean: "辅音 tr", group: "phu_am", file: "tr.mp3" },
    { word: "gi", mean: "辅音 gi", group: "phu_am", file: "gi.mp3" },
    { word: "ngh", mean: "辅音 ngh", group: "phu_am", file: "ngh.mp3" },

    // === BẢNG VẦN HÀNG 1 ===
    { word: "ia", mean: "Vần ia", group: "a", file: "ia.mp3" },
    { word: "ua", mean: "Vần ua", group: "a", file: "ua.mp3" },
    { word: "ưa", mean: "Vần ưa", group: "a", file: "ưa.mp3" },
    { word: "ao", mean: "Vần ao", group: "a", file: "ao.mp3" },
    { word: "eo", mean: "Vần eo", group: "a", file: "eo.mp3" },
    { word: "au", mean: "Vần au", group: "a", file: "au.mp3" },
    { word: "êu", mean: "Vần êu", group: "a", file: "êu.mp3" },
    { word: "iu", mean: "Vần iu", group: "a", file: "iu.mp3" },
    { word: "ưu", mean: "Vần ưu", group: "a", file: "ưu.mp3" },
    { word: "ai", mean: "Vần ai", group: "a", file: "ai.mp3" },
    { word: "oi", mean: "Vần oi", group: "a", file: "oi.mp3" },
    { word: "ôi", mean: "Vần ôi", group: "a", file: "ôi.mp3" },
    { word: "ơi", mean: "Vần ơi", group: "a", file: "ơi.mp3" },
    { word: "ui", mean: "Vần ui", group: "a", file: "ui.mp3" },

    // === BẢNG VẦN HÀNG 2 ===
    { word: "ưi", mean: "Vần ưi", group: "e", file: "ưi.mp3" },
    { word: "ay", mean: "Vần ay", group: "e", file: "ay.mp3" },
    { word: "ây", mean: "Vần ây", group: "e", file: "ây.mp3" },
    { word: "ac", mean: "Vần ac", group: "e", file: "ac.mp3" },
    { word: "ăc", mean: "Vần ăc", group: "e", file: "ăc.mp3" },
    { word: "oc", mean: "Vần oc", group: "e", file: "oc.mp3" },
    { word: "ôc", mean: "Vần ôc", group: "e", file: "ôc.mp3" },
    { word: "uc", mean: "Vần uc", group: "e", file: "uc.mp3" },
    { word: "ưc", mean: "Vần ưc", group: "e", file: "ưc.mp3" },
    { word: "at", mean: "Vần at", group: "e", file: "at.mp3" },
    { word: "ăt", mean: "Vần ăt", group: "e", file: "ăt.mp3" },
    { word: "ât", mean: "Vần ât", group: "e", file: "ât.mp3" },
    { word: "et", mean: "Vần et", group: "e", file: "et.mp3" },
    { word: "êt", mean: "Vần êt", group: "e", file: "êt.mp3" },

    // === BẢNG VẦN HÀNG 3 ===
    { word: "it", mean: "Vần it", group: "i", file: "it.mp3" },
    { word: "ot", mean: "Vần ot", group: "i", file: "ot.mp3" },
    { word: "ôt", mean: "Vần ôt", group: "i", file: "ôt.mp3" },
    { word: "ơt", mean: "Vần ơt", group: "i", file: "ơt.mp3" },
    { word: "ut", mean: "Vần ut", group: "i", file: "ut.mp3" },
    { word: "ứt", mean: "Vần ứt", group: "i", file: "ứt.mp3" },
    { word: "an", mean: "Vần an", group: "i", file: "an.mp3" },
    { word: "ăn", mean: "Vần ăn", group: "i", file: "ăn.mp3" },
    { word: "ân", mean: "Vần ân", group: "i", file: "ân.mp3" },
    { word: "en", mean: "Vần en", group: "i", file: "en.mp3" },
    { word: "ên", mean: "Vần ên", group: "i", file: "ên.mp3" },
    { word: "in", mean: "Vần in", group: "i", file: "in.mp3" },
    { word: "on", mean: "Vần on", group: "i", file: "on.mp3" },
    { word: "ôn", mean: "Vần ôn", group: "i", file: "ôn.mp3" },
    { word: "ơn", mean: "Vần ơn", group: "i", file: "ơn.mp3" },

    // === BẢNG VẦN HÀNG 4 ===
    { word: "un", mean: "Vần un", group: "o", file: "un.mp3" },
    { word: "ang", mean: "Vần ang", group: "o", file: "ang.mp3" },
    { word: "ăng", mean: "Vần ăng", group: "o", file: "ăng.mp3" },
    { word: "âng", mean: "Vần nâng", group: "o", file: "âng.mp3" },
    { word: "ong", mean: "Vần ong", group: "o", file: "ong.mp3" },
    { word: "ông", mean: "Vần ông", group: "o", file: "ông.mp3" },
    { word: "ung", mean: "Vần ung", group: "o", file: "ung.mp3" },
    { word: "ưng", mean: "Vần ưng", group: "o", file: "ưng.mp3" },
    { word: "ach", mean: "Vần ach", group: "o", file: "ach.mp3" },
    { word: "êch", mean: "Vần êch", group: "o", file: "êch.mp3" },
    { word: "ich", mean: "Vần ich", group: "o", file: "ich.mp3" },
    { word: "am", mean: "Vần am", group: "o", file: "am.mp3" },
    { word: "ăm", mean: "Vần ăm", group: "o", file: "ăm.mp3" },
    { word: "âm", mean: "Vần âm", group: "o", file: "âm.mp3" },
    { word: "em", mean: "Vần em", group: "o", file: "em.mp3" },

    // === BẢNG VẦN HÀNG 5 ===
    { word: "êm", mean: "Vần êm", group: "u", file: "êm.mp3" },
    { word: "om", mean: "Vần om", group: "u", file: "om.mp3" },
    { word: "ôm", mean: "Vần ôm", group: "u", file: "ôm.mp3" },
    { word: "ơm", mean: "Vần ơm", group: "u", file: "ơm.mp3" },
    { word: "im", mean: "Vần im", group: "u", file: "im.mp3" },
    { word: "um", mean: "Vần um", group: "u", file: "um.mp3" },
    { word: "ap", mean: "Vần ap", group: "u", file: "ap.mp3" },
    { word: "ăp", mean: "Vần ăp", group: "u", file: "ăp.mp3" },
    { word: "âp", mean: "Vần âp", group: "u", file: "âp.mp3" },
    { word: "ep", mean: "Vần ep", group: "u", file: "ep.mp3" },
    { word: "êp", mean: "Vần êp", group: "u", file: "êp.mp3" },
    { word: "op", mean: "Vần op", group: "u", file: "op.mp3" },
    { word: "ôp", mean: "Vần ôp", group: "u", file: "ôp.mp3" },
    { word: "ơp", mean: "Vần ơp", group: "u", file: "ơp.mp3" },
    { word: "ip", mean: "Vần ip", group: "u", file: "ip.mp3" },

    // === BẢNG VẦN HÀNG MỞ RỘNG ===
    { word: "up", mean: "Vần up", group: "u", file: "up.mp3" },
    { word: "anh", mean: "Vần anh", group: "u", file: "anh.mp3" },
    { word: "ênh", mean: "Vần ênh", group: "u", file: "ênh.mp3" },
    { word: "inh", mean: "Vần inh", group: "u", file: "inh.mp3" },
    { word: "iêu", mean: "Vần iêu", group: "u", file: "iêu.mp3" },
    { word: "yêu", mean: "Vần yêu", group: "u", file: "yêu.mp3" },
    { word: "uôi", mean: "Vần uôi", group: "u", file: "uôi.mp3" },
    { word: "ươi", mean: "Vần ươi", group: "u", file: "ươi.mp3" },
    { word: "iêc", mean: "Vần iêc", group: "u", file: "iêc.mp3" },
    { word: "uôc", mean: "Vần uôc", group: "u", file: "uôc.mp3" },
    { word: "ươc", mean: "Vần ươc", group: "u", file: "ươc.mp3" },
    { word: "iêt", mean: "Vần iêt", group: "u", file: "iêt.mp3" },
    { word: "yêt", mean: "Vần yêt", group: "u", file: "yêt.mp3" },
    { word: "uôt", mean: "Vần uôt", group: "u", file: "uôt.mp3" },
    { word: "ươt", mean: "Vần ươt", group: "u", file: "ươt.mp3" },
    { word: "iên", mean: "Vần iên", group: "u", file: "iên.mp3" },
    { word: "yên", mean: "Vần yên", group: "u", file: "yên.mp3" },
    { word: "uôn", mean: "Vần uôn", group: "u", file: "uôn.mp3" },
    { word: "ươn", mean: "Vần ươn", group: "u", file: "ươn.mp3" },
    { word: "iêm", mean: "Vần iêm", group: "u", file: "iêm.mp3" },
    { word: "yêm", mean: "Vần yêm", group: "u", file: "yêm.mp3" },
    { word: "uôm", mean: "Vần uôm", group: "u", file: "uôm.mp3" },
    { word: "iêp", mean: "Vần iêp", group: "u", file: "iêp.mp3" },
    { word: "ươp", mean: "Vần ươp", group: "u", file: "ươp.mp3" },
    { word: "oa", mean: "Vần oa", group: "u", file: "oa.mp3" },
    { word: "oe", mean: "Vần oe", group: "u", file: "oe.mp3" },
    { word: "uê", mean: "Vần uê", group: "u", file: "uê.mp3" },
    { word: "uy", mean: "Vần uy", group: "u", file: "uy.mp3" },
    { word: "oai", mean: "Vần oai", group: "u", file: "oai.mp3" },
    { word: "oay", mean: "Vần oay", group: "u", file: "oay.mp3" },
    { word: "oac", mean: "Vần oac", group: "u", file: "oac.mp3" },
    { word: "oat", mean: "Vần oat", group: "u", file: "oat.mp3" },
    { word: "oan", mean: "Vần oan", group: "u", file: "oan.mp3" },
    { word: "uân", mean: "Vần uân", group: "u", file: "uân.mp3" },
    { word: "uyt", mean: "Vần uyt", group: "u", file: "uyt.mp3" },
    { word: "oăt", mean: "Vần oăt", group: "u", file: "oăt.mp3" },
    { word: "uât", mean: "Vần uât", group: "u", file: "uât.mp3" },
    { word: "oam", mean: "Vần oam", group: "u", file: "oam.mp3" },
    { word: "oap", mean: "Vần oap", group: "u", file: "oap.mp3" },
    { word: "uyp", mean: "Vần uyp", group: "u", file: "uyp.mp3" },
    { word: "oeo", mean: "Vần oeo", group: "u", file: "oeo.mp3" },
    { word: "uyu", mean: "Vần uyu", group: "u", file: "uyu.mp3" },
    { word: "iêng", mean: "Vần iêng", group: "u", file: "iêng.mp3" },
    { word: "yêng", mean: "Vần yêng", group: "u", file: "yêng.mp3" },
    { word: "uông", mean: "Vần uông", group: "u", file: "uông.mp3" },
    { word: "ương", mean: "Vần hương", group: "u", file: "ương.mp3" },
    { word: "oang", mean: "Vần oang", group: "u", file: "oang.mp3" },
    { word: "uyên", mean: "Vần uyên", group: "u", file: "uyên.mp3" },
    { word: "uyêt", mean: "Vần uyêt", group: "u", file: "uyêt.mp3" },
    { word: "oanh", mean: "Vần oanh", group: "u", file: "oanh.mp3" },
    { word: "uynh", mean: "Vần uynh", group: "u", file: "uynh.mp3" },
    { word: "uych", mean: "Vần uych", group: "u", file: "uych.mp3" },
    { word: "oăng", mean: "Vần oăng", group: "u", file: "oăng.mp3" },
    { word: "uâng", mean: "Vần uâng", group: "u", file: "uâng.mp3" },
    { word: "oong", mean: "Vần oong", group: "u", file: "oong.mp3" }
];
